apiVersion: apps/v1
kind: Deployment
metadata:
  name: pststore
  labels:
    app: pststore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pststore
  template:
    metadata:
      labels:
        app: pststore
    spec:
      containers:
        - name: pststore
          image: docker.io/stetinapavel/publicstore:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
